name: Build tacos backend Application

on:
  push:
    paths:
      - 'tacos/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tacos
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - name: Build the app
        run: ./gradlew build --no-daemon
